login_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth


urlpatterns = [
    path(
        'login/',
        auth.LoginView.as_view(
            template_name='login_app/login.html'
        ),
        name='login'),
    path(
        'logout/',
        auth.LogoutView.as_view(),
        name='logout'
    )
]

polls/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # path('', views.index, name='index'),
    path(
        'company/<int:pk>/details/',
        views.CompanyDetail.as_view(),
        name='company_details'
        ),
    path('', views.CompanyList.as_view(), name='companies_list'),
    path(
        'company/<int:pk>/details/work-create',
        views.WorkCreate.as_view(),
        name='work_create'
        ),
    path('workers/', views.WorkerList.as_view(), name='worker_list'),
    path(
        'workers/<int:pk>/detail',
        views.WorkerDetail.as_view(), name='worker_detail'
        ),
    path(
        'company/<int:pk>/manager',
        views.ManagerList.as_view(),
        name='manager_list'
    ),
    path(
        'workers/<int:pk>/detail/create',
        views.WorktimeCreate.as_view(),
        name='worktime_create'),
    path(
        'company/<int:company_id>/details/<int:work_id>',
        views.AssignWorker.as_view(),
        name='assign_worker')
]

polls_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('', include('login_app.urls'))
]

login_app/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here.


NEW = 1
APPROVED = 2
CANCELLED = 3
FINISHED = 4


class Company(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Manager(models.Model):
    name = models.CharField(max_length=200)
    com_name = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Worker(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Work(models.Model):
    name = models.CharField(max_length=200)
    com_name = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class WorkPlace(models.Model):
    name = models.CharField(max_length=200)
    worker_name = models.OneToOneField(
        Worker, on_delete=models.CASCADE, primary_key=True
        )
    work_name = models.ForeignKey(Work, on_delete=models.CASCADE)
    choice = [
        (NEW, 'New'),
        (APPROVED, 'Approved'),
        (CANCELLED, 'Cancelled'),
        (FINISHED, 'Finished'),
        ]
    status = models.IntegerField(choices=choice)

    def __str__(self):
        return self.name


class WorkTime(models.Model):
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    choice = [
        (NEW, 'New'),
        (APPROVED, 'Approved'),
        (CANCELLED, 'Cancelled'),
        ]
    status = models.IntegerField(choices=choice, default=NEW)
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
    work = models.ForeignKey(Work, on_delete=models.CASCADE)

polls/forms.py
from django import forms
from .models import Work, WorkTime, WorkPlace


class WorkCreate(forms.ModelForm):
    class Meta:
        model = Work
        fields = ['name', 'com_name']


class WorktimeCreateForm(forms.ModelForm):
    class Meta:
        model = WorkTime
        fields = ['worker', 'work', 'date_start', 'date_end', 'status']


class AssignWorkerForm(forms.ModelForm):
    class Meta:
        model = WorkPlace
        fields = [
            'name',
            'worker_name',
            'work_name',
            'status',
        ]

login_app/views.py
from django.shortcuts import render

# Create your views here.

polls/views.py
from django.shortcuts import get_object_or_404
from .models import (
    Company, Work, Worker, WorkTime, Manager
    )
from .forms import (
    WorkCreate, WorktimeCreateForm, AssignWorkerForm
)
from django.views.generic import (
    CreateView, ListView, DetailView
)
from django.urls import reverse_lazy
import logging


logger = logging.getLogger('sentry_logger')


class CompanyList(ListView):
    model = Company
    template_name = 'polls/company_list.html'
    context_object_name = 'companies'


class ManagerList(ListView):
    model = Manager
    template_name = 'polls/manager_list.html'
    context_object_name = 'managers'

    def get_queryset(self):
        com_name = get_object_or_404(Company, id=self.kwargs.get('pk'))
        return Manager.objects.filter(com_name=com_name)


class CompanyDetail(DetailView):
    model = Company
    template_name = 'polls/companies_details.html'
    context_object_name = 'company'


class WorkerList(ListView):
    model = Worker
    template_name = 'polls/worker_list.html'
    context_object_name = 'worker_list'


class WorkerDetail(DetailView):
    model = Worker
    template_name = 'polls/worker_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        worker = get_object_or_404(Worker, pk=self.kwargs.get('pk'))
        context['worktimes'] = WorkTime.objects.filter(worker=worker)
        # context['works'] = Work.objects.filter(worktime__worker=worker)
        return context


class WorktimeCreate(CreateView):
    template_name = 'polls/worktime_create.html'
    form_class = WorktimeCreateForm

    def get_success_url(self):
        worker_id = self.kwargs.get('pk')
        return reverse_lazy('worker_detail', kwargs={'pk': worker_id})

    def get_initial(self):
        worker = get_object_or_404(Worker, id=self.kwargs.get('pk'))
        return {'worker': worker}

    def form_valid(self, form):
        form.save()
        data = self.request.POST
        logger.debug(
            'start: %s, end: %s, worker: %s, status:%s',
            data['date_start'], data['date_end'], data['worker'],
            data['status'])
        logger.info('worktime create')
        return super().form_valid(form)


class WorkCreate(CreateView):
    template_name = 'polls/create_work.html'
    form_class = WorkCreate

    def get_success_url(self):
        company_id = self.kwargs.get('pk')
        return reverse_lazy('company_details', kwargs={'pk': company_id})

    def get_initial(self):
        self.company = get_object_or_404(Company, id=self.kwargs.get('pk'))
        return {'com_name': self.company}

    def form_valid(self, form):
        form.save()
        data = self.request.POST
        # print(data)
        logger.debug(
            'name work: %s, company name: %s',
            data['name'], data['com_name']
        )
        logger.info('create work')
        return super().form_valid(form)

    


class AssignWorker(CreateView):
    template_name = 'polls/assign_worker.html'
    form_class = AssignWorkerForm

    def get_initial(self):
        work_name = get_object_or_404(Work, id=self.kwargs.get('work_id'))
        return {'work_name': work_name}

    def get_success_url(self):
        company_id = self.kwargs.get('company_id')
        return reverse_lazy('company_details', kwargs={'pk': company_id})

    def form_valid(self, form):
        form.save()
        data = self.request.POST
        logger.debug('worker: %s, work:%s',
                    data['worker_name'], data['work_name'])
        logger.info('assign worker')
        return super().form_valid(form)

login_app/templates/login_app/login.html
{%extends 'polls/index.html'%}
{%block content%}
    <div class="box">
        <h2 class="title">Login</h2>
        <form action="" method="POST">
            {%csrf_token%}
            {{form.as_ul}}
            
            <input class="create" type="submit" value="Log in">
        </form>
    </div>
{%endblock%}

polls/templates/polls/assign_worker.html
{%extends 'polls/index.html'%}
{%block content%}
<div class="box"></div>
{%if perms.polls.add_workplace%}
    
        <h2 class="title">Assign worker</h1>
        <form action="" method="POST">
            <ul>
                {%csrf_token%}
                {{form.as_ul}}
            </ul>
            <input class="create" type="submit" value="Assign">
        </form>
    
{%else%}
    <h2 class="title">Нет прав</h2>
{%endif%}
</div>
{%endblock%}

polls/templates/polls/companies_details.html
{%extends 'polls/index.html'%}
{%block menu%}
    <li><a href="{%url 'manager_list' company.id%}">Manager List</a></li>
{%endblock%}
{%block content%}
<!-- {{perms.polls}} -->
{%if perms.polls.view_work%}
{% if company.work_set.all %}
    <div class = 'box'>
        <h2 class="title">{{company.name}}</h2>
        <ul class='company-list'>
                {% for work in company.work_set.all %}
                    <li class='company-list-item'>
                        <span class="text">{{ work.name }}</span>
                        <ul>
                            {% if work.workplace_set.all%}
                            {% for workplace in work.workplace_set.all%}
                            <ul>
                                <li class="text">{{ workplace.name }}</li>
                            </ul>
                            <ul>
                                <li class="text">{{ workplace.worker_name}}</li>
                            </ul>
                            {% endfor %}
                            {%else%}
                                <ul>
                                    <li class="text">Unidentified workplace</li>
                                </ul>
                            {%endif%}
                            <div class="assign">
                                <a class="" href="{%url 'assign_worker' company_id=company.id work_id=work.id%}">Assign worker</a>
                            </div>
                                
                            
                        </ul>
                    </li>
                {% endfor %}
            </ul>
{%endif%}
        <div class="buttom">
            <a class='text' href="{% url 'work_create' company.id %}">Create new job</a>
        </div>
    </div>
{%else%}
<div class="box">
    <h2 class="title"> У вас нет прав на просмотр данной страницы</h2>
</div>
{%endif%}
{%endblock%}

polls/templates/polls/company_list.html
{%extends 'polls/index.html'%}
{%block title%}Companies list{%endblock%}
{%block content%}
    <div class='box'>
        <h2 class='title'>Companies list</h2>
        <ul class='company-list'>
            {%if user.is_authenticated%}
                {%for company in companies%}
                    <li class='company-list-item'><a class="text" href="{%url 'company_details' company.pk%}">{{company.name}}</a></li>
                {%endfor%}
            {%else%}
                <h2 class="title">Для просмотра информации войдите в систему</h2>
            {%endif%}
        </ul>
    </div>
{%endblock%}

polls/templates/polls/create_work.html
{%extends 'polls/index.html'%}
{%block content%}
<div class="box">
    {%if perms.polls.add_work%}
        <h2 class="title">Create work</h2>   
        <form action="" method="POST">
            <div class='form'>
                <ul>
                    {%csrf_token%}
                    {{form.as_ul}}
                </ul>
                <input class="create" type="submit" value="Create">
            </div>
        </form>
    {%else%}
    <h2 class="title">Нет прав</h2>
    {%endif%}
</div>
{%endblock%}

polls/templates/polls/detail.html
<h2> {{ company.name }}</h2>

{% if company.work_set.all%}
    <ul>
        {% for work in company.work_set.all %}
            <li>
                {{ work.name }}
                <ul>
                    {% for workplace in work.workplace_set.all%}
                    <li>{{ workplace.name }}</li>
                    <ul>
                        <li>{{ workplace.worker_name}}</li>
                    </ul>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endif %}

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type ="text/css" href="{% static 'polls/style.css' %}">

<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
      <header>
        <nav>
          <menu>
            <li><a href="{%url 'companies_list' %}">Companies list</a></li>
            <li><a href="{%url 'worker_list'%}">Worker list</a></li>
            {%block menu%}{%endblock%}
            {%if user.is_authenticated%}
              <li class="login"><a href="{%url 'logout'%}">{{user.username }} | Log OUT</a></li>
            {%else%}
              <li class="login"><a href="{% url 'login'%}">Login</a></li>
            {%endif%}
          </menu>
        </nav>
      </header>
      <main>
        {%block content%}
        {%endblock%}
      </main>
  </body>
</html>

polls/templates/polls/manager_list.html
{%extends 'polls/index.html'%}
{%block content%}
<div class="box">
{%if managers.all%}  
    
        <h2 class="title">Manager list</h2>
        <ul class="company-list">
            {%for manager in managers%}
                <li class="company-list-item"><span class="text">{{manager.name}}</span></li>
            {%endfor%}
        </ul>
    
{%else%}
    <h2 class="title">Empty</h2>
</div>
{%endif%}
{%endblock%}

polls/templates/polls/worker_detail.html
{%extends 'polls/index.html'%}
{%block content%}
<div class="box">
    <h2>Worker name: {{worker.name}}</h2>
    <ul class="Company-list">
        {%for worktime in worktimes%}    
            <li class="company-list-item">
                
                <p class="text">Work: {{worktime.work.name}}</p>
                
                    <p class="text">Start: {{worktime.date_start|date:"SHORT_DATE_FORMAT"}}</p>
                    <p class="text">End: {{worktime.date_end|date:"SHORT_DATE_FORMAT"}}</p>
                    <p class="text">Status: {{worktime.status}}</p>
                
            </li>
        {%endfor%}
    
    </ul>    
    <div class="create">
        <a href="{%url 'worktime_create' worker.id%}" class="text">Create time</a>
    </div>
    
</div>
{%endblock%}

polls/templates/polls/worker_list.html
{%extends 'polls/index.html'%}
{%block content%}
    <div class='box'>
        <h2 class="title">Worker list</h2>
        <ul class="company-list">
            {%for worker in worker_list%}
                <li class="company-list-item">
                    <a class='text' href="{%url 'worker_detail' worker.id%}">{{worker.name}}</a>
                </li>
            {%endfor%}
        </ul>
    </div>
{%endblock%}

polls/templates/polls/worktime_create.html
{%extends 'polls/index.html'%}
{%block content%}
<div class="box">
        <h2 class="title">Create worktime</h2>   
        <form action="" method="POST">
            <div class='form'>
                <ul>
                    {%csrf_token%}
                    {{form.as_ul}}
                </ul>
                <input class="create" type="submit" value="Create">
            </div>
        </form>
</div>
{%endblock%}